"""initial migration

Revision ID: c5e6a88c37c7
Revises: 
Create Date: 2024-07-26 00:30:48.008518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c5e6a88c37c7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    users = op.create_table('users',
                            sa.Column('id', sa.Integer(), nullable=False),
                            sa.Column('first_name', sa.String(length=64), nullable=False),
                            sa.Column('surname', sa.String(length=128), nullable=False),
                            sa.Column('email', sa.String(length=128), nullable=False),
                            sa.Column('password', sa.String(length=128), nullable=False),
                            sa.Column('is_admin', sa.Boolean(), nullable=False),
                            sa.PrimaryKeyConstraint('id')
                            )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    wallets = op.create_table('wallets',
                              sa.Column('id', sa.Integer(), nullable=False),
                              sa.Column('balance', sa.Float(), nullable=False),
                              sa.Column('user_id', sa.Integer(), nullable=False),
                              sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                              sa.PrimaryKeyConstraint('id')
                              )
    op.create_index(op.f('ix_wallets_id'), 'wallets', ['id'], unique=False)
    op.create_table('transactions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('amount', sa.Float(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('wallet_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.bulk_insert(users, [
        {'first_name': 'John', 'surname': 'Doe', 'email': 'testemail1@mail.ru',
         'password': '$2b$12$7V9TZUs/ljtq6LJLoWJQ.e.aUfz1IMIqFyFcqqfBQRcj9d5hc4AVu',
         'is_admin': True},
        {'first_name': 'Jane', 'surname': 'Doe', 'email': 'testemail2@mail.ru',
         'password': '$2b$12$ErIn0ZSFkfzS6BItmZ8GyOhGTDuB/.bt/4Un84cUfiiggOk0FRbEO',
         'is_admin': False},
    ])
    op.bulk_insert(wallets, [
        {'user_id': 2, 'balance': 0},
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_wallets_id'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
